### ISSUE TITLE
snapframework favicon.ico to templates

### ISSUE THREAD

**Issue by gspia** [snapframework/snap-templates#14]
Hi
Could you please add favicon.ico to each template into the static directories of the default, barebones and tutorial -templates. This way the access.log would be cleaner from the very beginning and maybe it is easier to someone then change the icon, too.
[favicon.zip](https://github.com/snapframework/snap-templates/files/324846/favicon.zip)

**Comment by mightybyte** [comment]
I won't be able to get to this right away because the current template generator doesn't support binary files.

**Comment by gspia** [comment]
Ok & thanks for informing about this (I'll close this issue so that it won't hang around).
