### ISSUE TITLE
Snap init dependencies are not all present in any Stackage LTS

### ISSUE THREAD

**Issue by d6e** [snapframework/snap-templates#20]
Following the instructions from the site, I try to use `snap init` followed by `stack init` to install those packages and stack complains that there's no compatible LTS with all the dependencies available.

**Comment by d6e** [comment]
I should note `cabal install --only-dependencies` also fails given the dependency bounds `snap init` produces:
```
  Build-depends:
    bytestring                >= 0.9.1   && < 0.11,
    heist                     >= 1.0     && < 1.1,
    map-syntax                >= 0.2     && < 0.3,
    monad-control             >= 1.0     && < 1.1,
    mtl                       >= 2       && < 2.3,
    snap                      >= 1.0     && < 1.1,
    snap-core                 >= 1.0     && < 1.1,
    snap-server               >= 1.0     && < 1.1,
    snap-loader-static        >= 1.0     && < 1.1,
    text                      >= 0.11    && < 1.3,
    time                      >= 1.1     && < 1.9,
    xmlhtml                   >= 0.1     && < 0.3
```

**Comment by mightybyte** [comment]
Hi, thanks for the report.  I just bumped the versions in the project templates and released a new version to hackage.  Try downloading `snap-templates` again and then re-creating the project templates.  It should build fine with `cabal install`.  I'll close this issue for now, but if you encounter any problems, feel free to reopen.
